name=arduino-NextPM
version=1.0.0
author=Hubert
maintainer=Hubert
sentence=Library for NextPM sensor in UART and RS485 Modbus RTU.
paragraph=This library supports NextPM communication in direct UART and RS485 Modbus RTU.
category=Sensors
url=https://example.com
architectures=*
depends=ModbusRTUMaster